name: Portfolio
on:
  push:
    branches: [master]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}

    steps:
      # STEP 1: checkout the repo code
      - name: Checkout Code
        uses: actions/checkout@v4

      # STEP 2: configure GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # STEP 3: upload static files as a Pages artifact
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # STEP 4: deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4